#include "timers.h"
#include "qutils.h"
#include "dataenums.h"
#include "dataset.h"
#include "jasptheme.h"
#include "columnmodel.h"
#include "columnutils.h"
#include "datasetpackage.h"
#include "jaspclient/dataedit.h"
#include "log.h"
#include "gui/preferencesmodel.h"

ColumnModel::ColumnModel() : QIdentityProxyModel(DataSetPackage::pkg())
{
	// The excision, Cut 7: the shownFilterChanged/allFiltersReset/workspaceEmptyValuesChanged
	// relays died with the label editor QML (label-filter state rode the legacy Column).
	connect(DataSetPackage::pkg(),	&DataSetPackage::datasetChanged,				this, &ColumnModel::checkCurrentColumn		     );
	connect(DataSetPackage::pkg(),	&DataSetPackage::chooseColumn,					this, &ColumnModel::setChosenColumn		     );
	connect(DataSetPackage::pkg(),	&DataSetPackage::shownDataSetChanged,			this, &ColumnModel::shownDataSetChangedHandler	);
}

QVariant ColumnModel::columnTypeFriendlyMapping(computedColumnType compColT)
{
	typedef QMap<QString, QVariant> localMap;
	// The excision, Cut 5: Column::columnTypeFriendlyName died with Column — the strings
	// move here verbatim (computed columns return as derivations, menu stays for then).
	const QString friendly =
			compColT == computedColumnType::notComputed		? QObject::tr("Not computed")
		:	compColT == computedColumnType::rCode			? QObject::tr("Computed with R code")
		:	compColT == computedColumnType::constructorCode	? QObject::tr("Computed with drag-and-drop")
		:	compColT == computedColumnType::analysis		? QObject::tr("Column generated by analysis")
		:	compColT == computedColumnType::analysisNotComputed ? QObject::tr("Column added by analysis")
		:	QString();
	
	return	localMap(
			{	
				std::make_pair("value", computedColumnTypeToQString(compColT)),		
				std::make_pair("label", friendly)	
			});
}

QVariantList ColumnModel::computedTypeValues() const
{
	// The excision, Cut 5: the code type came from the chosen legacy Column — computed
	// columns return as derivations, so the menu shows the notComputed set.
	switch(computedColumnType::notComputed)
	{
	case computedColumnType::notComputed:
	case computedColumnType::rCode:
	case computedColumnType::constructorCode:
		return { columnTypeFriendlyMapping(computedColumnType::notComputed), columnTypeFriendlyMapping(computedColumnType::rCode), columnTypeFriendlyMapping(computedColumnType::constructorCode) };

	case computedColumnType::analysis:
		return  { columnTypeFriendlyMapping(computedColumnType::analysis) };

	case computedColumnType::analysisNotComputed:
		return { columnTypeFriendlyMapping(computedColumnType::analysisNotComputed), columnTypeFriendlyMapping(computedColumnType::notComputed), columnTypeFriendlyMapping(computedColumnType::rCode), columnTypeFriendlyMapping(computedColumnType::constructorCode) };;
	}
	
	return {};
}

QVariantList ColumnModel::columnTypeValues() const
{
	typedef QMap<QString, QVariant> localMap;
	
	return {
		localMap({ std::make_pair("value", columnTypeToQString(columnType::scale)),				std::make_pair("label", QObject::tr("Scale")),		std::make_pair("columnTypeIcon", JaspTheme::currentIconPath() + "variable-scale.svg")	}),
		localMap({ std::make_pair("value", columnTypeToQString(columnType::ordinal)),			std::make_pair("label", QObject::tr("Ordinal")),	std::make_pair("columnTypeIcon", JaspTheme::currentIconPath() + "variable-ordinal.svg")	}),
		localMap({ std::make_pair("value", columnTypeToQString(columnType::nominal)),			std::make_pair("label", QObject::tr("Nominal")),	std::make_pair("columnTypeIcon", JaspTheme::currentIconPath() + "variable-nominal.svg")	})
	};
}

QString ColumnModel::columnNameQ()
{
	if (_virtual) return _dummyColumn.name;

	// NEO adapter: the SCHEMA is the name truth — the mirror never renames, so its name
	// goes stale the moment a NEO rename lands (the "edit didn't stick" disease).
	if (const ColumnInfo * info = laneSchemaColumn())
		return QString::fromStdString(info->name);

	return "";
}


void ColumnModel::setColumnNameQ(QString newColumnName)
{
	if (_beingRefreshed || newColumnName == columnNameQ()) return;

	// NEO (R2 write-routing): the commit is a wire op, never a legacy Column command — the
	// mirror is grow-only metadata; a rename there would silently diverge from the lane
	// schema the grid renders. The virtual branch is the worst legacy offender (it inserts
	// ghost Columns with no null guard at all): one insert_cols replaces the whole macro.
	DataSet * neoDataSet = DataSetPackage::pkg()->dataSet();
	if (neoDataSet && neoDataSet->isOpen())
	{
		if (_virtual)
		{
			// The editor's position, clamped to the schema extent (a -1 index appends).
			const uint64_t at = (_columnIndex >= 0 && size_t(_columnIndex) <= neoDataSet->schema().size())
								? uint64_t(_columnIndex) : uint64_t(neoDataSet->schema().size());
			undoStack()->endMacro(new DataEditCommand(
				neoDataSet,
				DataEdit::insertColsOp(at, fq(newColumnName), _dummyColumn.type),
				QByteArray(),
				tr("Insert column")));
		}
		else
		{
			// The chosen column by SCHEMA identity: the lane mirror is grown in schema order
			// but never RENAMED, so its names go stale after prior NEO renames — the index is
			// the stable correspondence (chosenColumn() is the mirror index).
			const int idx = chosenColumn();
			const ColumnInfo * info = idx >= 0 ? neoDataSet->schemaColumnAt(size_t(idx)) : nullptr;
			if (info)
				undoStack()->endMacro(new DataEditCommand(
					neoDataSet,
					DataEdit::schemaChangeRenameOp(neoDataSet, info->name, fq(newColumnName)),
					QByteArray(),
					tr("Rename column")));
			else
				Log::log() << "ColumnModel::setColumnNameQ: chosen column not found in the lane schema — rename refused" << std::endl;
		}
		return;
	}

	if (_virtual)
	{
		// Legacy insert-at-index flow — lane datasets are handled above (insertColsOp /
		// schemaChangeRenameOp and return). Nothing to do here anymore.
	}
}

QString ColumnModel::columnTitle() const
{
	if (_virtual) return _dummyColumn.title;

	// NEO adapter: display_name IS the "Long name" (P4) — the schema is its truth.
	if (const ColumnInfo * info = laneSchemaColumn())
		return QString::fromStdString(info->displayName);

	return "";
}

void ColumnModel::setColumnTitle(const QString & newColumnTitle)
{
	if (_beingRefreshed)
		return;

	// NEO: "Long name" IS the wire display_name — the same rename gesture as the Name
	// field (P4 couples them: declaring display_name derives the field name).
	// NEO: "Long name" IS the wire display_name; declaring it renames (P4 couples the
	// field name's derivation to it). Same op as the Name field — one gesture. The
	// equality guard matters here: the switch-time force-commit and focus-out handlers can
	// both re-fire with unchanged text, and a no-guard submit would mint a spurious
	// revision (and undo entry) on every such event.
	DataSet * neoDataSet = DataSetPackage::pkg()->dataSet();
	if (neoDataSet && neoDataSet->isOpen())
	{
		if (!_virtual && !newColumnTitle.isEmpty())
		{
			const int idx = chosenColumn();
			const ColumnInfo * info = idx >= 0 ? neoDataSet->schemaColumnAt(size_t(idx)) : nullptr;
			if (info && info->displayName != fq(newColumnTitle))
				undoStack()->endMacro(new DataEditCommand(
					neoDataSet,
					DataEdit::schemaChangeRenameOp(neoDataSet, info->name, fq(newColumnTitle)),
					QByteArray(),
					tr("Rename column")));
			else
				Log::log() << "ColumnModel::setColumnTitle: chosen column not found in the lane schema — rename refused" << std::endl;
		}
		return;
	}

	if (_virtual)
		_dummyColumn.title = newColumnTitle;
}

QString ColumnModel::columnDescription() const
{
	if (_virtual) return _dummyColumn.description;

	// NEO adapter: honest "" — the wire carries no description yet (it lands with the
	// labels editor as jasp:description field metadata).
	if (const ColumnInfo * info = laneSchemaColumn())
		return tq(info->description);

	return QString();
}

// The excision, Cut 7: computeFilter()/autoSort()/setAutoSort()/dropLevels() reads died with
// the label editor QML (compute filters return as derivations; autosort rides the B2 overlay;
// the lane dictionary never prunes).

int ColumnModel::rowsTotal() const
{
	return rowCount();	
}

int ColumnModel::rowCount(const QModelIndex &parent) const
{
	//The label-editor (and rowsTotal) present the column's *labels*, not its data rows. A (scale)
	//column's data lives in _dbls but only its non-empty labels are editable here, so the number of
	//rows a view should show is the number of labels, not the underlying row count.
	// The excision, Cut 5: the label editor's row count came from the Column's labels (B2).
	Q_UNUSED(parent);
	return 0;
}

// The excision, Cut 7: dropLevels()/resetEmptyValues() died with the label editor QML.

UndoStack *ColumnModel::undoStack()
{
	return UndoStack::singleton();
}


QVariantList ColumnModel::tabs() const
{
	// The excision, Cut 7: only "basicInfo" survives — computed (Cuts 4/5), the label editor
	// and per-column empty values (Cut 5) rode the legacy Column; they return as derivations /
	// the jasp:labels overlay (B2).
	QVariantList tabs;
	tabs.push_back(QMap<QString, QVariant>{  std::make_pair("name", "basicInfo"), std::make_pair("title", tr("Column definition"))});
	return tabs;
}


QString ColumnModel::currentColumnType() const
{
	if (_virtual) return columnTypeToQString(_dummyColumn.type);

	// NEO adapter: the schema's type (the mirror's goes stale after a NEO retype).
	if (const ColumnInfo * info = laneSchemaColumn())
		return columnTypeToQString(info->type);

	return columnTypeToQString(columnType::scale);
}

QString ColumnModel::computedType() const
{
	if (_virtual) return computedColumnTypeToQString(_dummyColumn.computedType);

	return computedColumnTypeToQString(computedColumnType::notComputed);
}

bool ColumnModel::computedTypeEditable() const
{
	if(_virtual)
		return true;

	// The excision, Cut 5: computed types lived on Columns — nothing to edit (derivations era).
	return false;
}

bool ColumnModel::isComputed() const
{
	if(_virtual)
		return false;

	// The excision, Cut 5: computed flags lived on Columns.
	return false;
}

void ColumnModel::setColumnDescription(const QString & newColumnDescription)
{
	if (_beingRefreshed)
		return;

	// NEO gate: description has no wire field yet (the lane never emits it; schema_change
	// has no entry key). Support lands with the labels-editor slice as jasp:description
	// field metadata — the same family as jasp:labels.
	DataSet * neoDataSet = DataSetPackage::pkg()->dataSet();
	if (neoDataSet && neoDataSet->isOpen())
	{
		Log::log() << "ColumnModel::setColumnDescription: description not yet on the lane wire — ignored (jasp:description lands with the labels editor)" << std::endl;
		return;
	}

	if (_virtual)
		_dummyColumn.description = newColumnDescription;
}

void ColumnModel::setColumnType(QString type)
{
	if (_beingRefreshed || type.isEmpty() || type == currentColumnType() || !columnTypeValidName(fq(type))) 
		return;

	columnType cType = columnTypeFromString(type.toStdString());

	// NEO (R2 write-routing): the variables-window dropdown is the THIRD type-switching
	// surface (the header menu + status-bar toggle route through the proxy since e2) —
	// same schema_change op, so all three surfaces agree on lane datasets.
	DataSet * neoDataSet = DataSetPackage::pkg()->dataSet();
	if (neoDataSet && neoDataSet->isOpen())
	{
		if (!_virtual && !DataEdit::wireTypeOf(cType).isEmpty())
		{
			const int idx = chosenColumn();
			const ColumnInfo * info = idx >= 0 ? neoDataSet->schemaColumnAt(size_t(idx)) : nullptr;
			if (info)
				undoStack()->endMacro(new DataEditCommand(
					neoDataSet,
					DataEdit::schemaChangeTypeOp(neoDataSet, { info->name }, cType),
					QByteArray(),
					tr("Change column type")));
			else
				Log::log() << "ColumnModel::setColumnType: chosen column not found in the lane schema — retype refused" << std::endl;
		}
		return;
	}

	if (_virtual)
		_dummyColumn.type = cType;

	// The excision, Cut 4: the legacy retype command is gone; lane retypes route through
	// the schema_change op above.
}

// The excision, Cut 7: getSortedSelection/setValueMaxWidth/setLabelMaxWidth died with the
// label editor QML (the selection set and the width caches were its).

bool ColumnModel::setData(const QModelIndex & index, const QVariant & value, int role)
{
	// The excision, Cut 7: the label-editor selection hook died with the label editor.
	Q_UNUSED(index);
	Q_UNUSED(value);
	Q_UNUSED(role);
	return false;
}

QVariant ColumnModel::data(	const QModelIndex & index, int role) const
{
	return QIdentityProxyModel::data(index, role > 0 ? role : int(dataPkgRoles::label));
}

QVariant ColumnModel::headerData(int section, Qt::Orientation orientation, int role) const
{
	// The excision, Cut 7: the rowWidth fallback (columnWidthFallback role) died with the
	// label editor's table view.
	Q_UNUSED(role);
	return !sourceModel() ? false : sourceModel()->headerData(section, orientation, role);
}

// The excision, Cut 7: refreshFilteredOut()/filteredOut()/resetFilterAllows() died with the
// label editor QML (per-column label-filter counts/flags rode the legacy Column).

void ColumnModel::setVisible(bool visible)
{
	//visible = visible && rowCount() > 0; //cannot show labels when there are no labels

	if (_visible == visible)
		return;

	_visible = visible;
	emit visibleChanged(_visible);
}

// The excision, Cut 5: the column() accessor + _column member died with Column — the
// schema (laneSchemaColumn()) is the chosen column's truth.

int ColumnModel::chosenColumn() const
{
	// No mirror Column exists on lane data — the maintained index is the truth (the
	// variables list binds this for its currentIndex).
	DataSet * laneDataSet = _shownDataSet ? _shownDataSet : DataSetPackage::pkg()->dataSet();
	if (laneDataSet && laneDataSet->isOpen())
		return _virtual ? -1 : _columnIndex;

	return -1;
}

void ColumnModel::setChosenColumnByName(const QString chosenNameQ, int colIndex)
{
	std::string chosenName = fq(chosenNameQ);
	// Always set the chosen column even if it is the same one: the ColumnModel might be not reset correctly when the dataset is closed.

	emit beforeChangingColumn(chosenNameQ);

	DataSet * data = DataSetPackage::pkg()->dataSet();
	clearVirtual();
	
	// Resolve by the SCHEMA name; the schema index becomes the chosen index (no mirror
	// Column exists to ask, R2 step 4; the Column itself died in Cut 5).
	int laneSchemaIdx = -1;
	if (data && data->isOpen())
		laneSchemaIdx = data->schemaColumnIndex(chosenName);

	// Virtual means NOT FOUND IN THE SCHEMA (leaving it null-based marked every clicked
	// lane column virtual: the editor showed an empty "new column" form and typing a name
	// INSERTED one instead of renaming).
	_virtual = laneSchemaIdx < 0;
	emit isVirtualChanged();
	
	_columnIndex = colIndex != -1 ? colIndex : laneSchemaIdx;
	if (laneSchemaIdx >= 0)
		_columnIndex = laneSchemaIdx;	// the schema index IS the chosen index

	refresh();
	notifyColumnChanged();
}

void ColumnModel::setChosenColumn(int columnIndex)
{
	// Resolve the index against the SCHEMA directly (the excision, Cut 5 removed the legacy
	// columnNameForIndex responder with the table model).
	DataSet * laneDataSet = _shownDataSet ? _shownDataSet : DataSetPackage::pkg()->dataSet();
	if (laneDataSet && laneDataSet->isOpen())
	{
		const ColumnInfo * info = columnIndex >= 0 ? laneDataSet->schemaColumnAt(size_t(columnIndex)) : nullptr;
		if (info)
		{
			setChosenColumnByName(tq(info->name));
			return;
		}
		// an index at/past the schema extent IS the virtual new-column slot — fall through
	}
	
	_columnIndex = columnIndex;
	
	_virtual = true;
	emit isVirtualChanged();
	
	refresh();
	notifyColumnChanged();
	
}

void ColumnModel::checkInsertedColumns(const QModelIndex &, int first, int)
{
	if (_columnIndex >= first)
	{
		_columnIndex = -1; // Force the setting of new column.
		setChosenColumn(first);
	}
}

void ColumnModel::checkRemovedColumns(int columnIndex, int count)
{
	int currentCol = chosenColumn();
	if ((columnIndex <= currentCol) && (currentCol < columnIndex + count))
	{
		setVisible(false);
		setChosenColumn(-1);
	}
}

void ColumnModel::checkCurrentColumn(int dataSetId, QStringList, QStringList missingColumns, QMap<QString, QString> changeNameColumns, bool, bool hasNewColumns)
{
	DataSet * current = DataSetPackage::pkg()->dataSet();
	if(!current || dataSetId != current->id())
		return;
	
	QString colName = columnNameQ();

	if (missingColumns.contains(colName))
	{
		setVisible(false);
		setChosenColumn(-1);
	}
	else
	{
		if (!_virtual && changeNameColumns.contains(colName))
			setColumnNameQ(changeNameColumns[colName]);
		if (hasNewColumns && _virtual && DataSetPackage::pkg()->dataSet()->columnCount() >= _columnIndex)
		{
			// The current column is not virtual anymore: reset it
			_columnIndex = -1;
			setChosenColumnByName(colName);
		}
	}
}

void ColumnModel::shownDataSetChangedHandler(DataSet * newDataSet)
{
	_shownDataSet = newDataSet;

	if(!newDataSet)
	{
		_virtual = true;
		emit isVirtualChanged();
		emit columnIsFilteredChanged();
		return;
	}

	// The excision, Cut 5: the labelFilterChanged hook died with the label editor guts.
	// NEO adapter: a lane edit lands as schemaChanged (applyRevision → landWireSchema) —
	// nothing bridges it to this model's legacy refresh chain (datasetChanged), so without
	// this hook the editor's fields would keep serving the pre-edit state forever.
	connect(newDataSet, &DataSet::schemaChanged, this, &ColumnModel::laneSchemaRefreshed, Qt::UniqueConnection);
}

const ColumnInfo * ColumnModel::laneSchemaColumn() const
{
	DataSet * dataSet = _shownDataSet ? _shownDataSet : DataSetPackage::pkg()->dataSet();
	if (!dataSet || !dataSet->isOpen())
		return nullptr;

	// The chosen column by SCHEMA index: _columnIndex is maintained by the choose paths
	// (setChosenColumn stores the view's index — schema order; setChosenColumnByName's
	// NEO branch stores schemaColumnIndex) — no mirror Column exists to ask (R2 step 4).
	return !_virtual && _columnIndex >= 0 ? dataSet->schemaColumnAt(size_t(_columnIndex)) : nullptr;
}

void ColumnModel::laneSchemaRefreshed()
{
	// Only the SHOWN dataset's schema matters (a background dataset landing must not
	// disturb the editor) — and only lane datasets fire this usefully.
	DataSet * dataSet = _shownDataSet ? _shownDataSet : DataSetPackage::pkg()->dataSet();
	if (dataSet && sender() == dataSet && dataSet->isOpen())
	{
		refresh();
		notifyColumnChanged();	// re-fires chosenColumnChanged/columnTitleChanged/… — the QML re-reads the schema
	}
}

void ColumnModel::refresh()
{
	beginResetModel();
	endResetModel();
}

void ColumnModel::notifyColumnChanged()
{
	emit chosenColumnChanged();
	emit nameEditableChanged();
	emit computedTypeChanged();
	emit computedTypeEditableChanged();
	emit computedTypeValuesChanged();
	emit columnTypeChanged();
	emit columnTypeValuesChanged();
	emit rowsTotalChanged();
	emit tabsChanged();
	emit columnIsFilteredChanged();
	// The editor-field properties (the R2 adapter rebinds ColumnBasicInfo's TextFields to
	// these): without these emits the Long-name/Description fields NEVER rebind
	// on a column switch — they kept serving the PREVIOUS column's values (the "infection"
	// seen as values that "keep and get set"). Name heals via chosenColumnChanged; these
	// two were simply missing from the notify set.
	emit columnTitleChanged();
	emit columnDescriptionChanged();
	// The excision, Cut 7: hasLabelsChanged/dropLevelsChanged/emptyValuesChanged and the
	// width-cache recompute died with the label editor QML.
}

// The excision, Cut 7: setSelected/removeAllSelected/unselectAll/setRowWidth died with the
// label editor QML — the whole per-label selection machinery was its.

bool ColumnModel::columnIsFiltered() const
{
	// The excision, Cut 5: label filters lived on Columns (B2).
	return false;
}

bool ColumnModel::nameEditable() const
{
	// The excision, Cut 5: analysis-owned computed Columns (whose names were locked) are gone.
	return true;
}

void ColumnModel::clearVirtual()
{
	_dummyColumn.description.clear();
	_dummyColumn.name.clear();
	_dummyColumn.title.clear();

	_dummyColumn.type			= columnType::scale;
	_dummyColumn.computedType	= computedColumnType::notComputed;
}

bool ColumnModel::compactMode() const
{
	return _compactMode;
}

void ColumnModel::setCompactMode(bool newCompactMode)
{
	if (_compactMode == newCompactMode)
		return;
	_compactMode = newCompactMode;
	emit compactModeChanged();
	emit tabsChanged();
}

void ColumnModel::languageChangedHandler()
{
	emit columnTypeValuesChanged();
	emit computedTypeValuesChanged();
	emit tabsChanged();
}

// The excision, Cut 7: isColumnNameFree died with CreateComputeColumnDialog (DataSet's schema
// predicate is the truth for the rename flows that return).
